- name: install JDK
  uses: actions/setup-java@v5
  with:
    distribution: temurin
    java-version: "21"
- name: install Linux build dependencies
  if: runner.os == 'Linux'
  run: sudo apt-get update && sudo apt-get install --yes libxcb1-dev
